// Code generated by protoc-gen-go. DO NOT EDIT.
// source: hasq_simple.proto

package main

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type HasqCreate struct {
	Sequence             int32    `protobuf:"varint,1,opt,name=sequence,proto3" json:"sequence,omitempty"`
	Token                string   `protobuf:"bytes,2,opt,name=token,proto3" json:"token,omitempty"`
	Key                  string   `protobuf:"bytes,3,opt,name=key,proto3" json:"key,omitempty"`
	Gen                  string   `protobuf:"bytes,4,opt,name=gen,proto3" json:"gen,omitempty"`
	Owner                string   `protobuf:"bytes,5,opt,name=owner,proto3" json:"owner,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HasqCreate) Reset()         { *m = HasqCreate{} }
func (m *HasqCreate) String() string { return proto.CompactTextString(m) }
func (*HasqCreate) ProtoMessage()    {}
func (*HasqCreate) Descriptor() ([]byte, []int) {
	return fileDescriptor_8f3733d4161a6cce, []int{0}
}

func (m *HasqCreate) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HasqCreate.Unmarshal(m, b)
}
func (m *HasqCreate) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HasqCreate.Marshal(b, m, deterministic)
}
func (m *HasqCreate) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HasqCreate.Merge(m, src)
}
func (m *HasqCreate) XXX_Size() int {
	return xxx_messageInfo_HasqCreate.Size(m)
}
func (m *HasqCreate) XXX_DiscardUnknown() {
	xxx_messageInfo_HasqCreate.DiscardUnknown(m)
}

var xxx_messageInfo_HasqCreate proto.InternalMessageInfo

func (m *HasqCreate) GetSequence() int32 {
	if m != nil {
		return m.Sequence
	}
	return 0
}

func (m *HasqCreate) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

func (m *HasqCreate) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *HasqCreate) GetGen() string {
	if m != nil {
		return m.Gen
	}
	return ""
}

func (m *HasqCreate) GetOwner() string {
	if m != nil {
		return m.Owner
	}
	return ""
}

type HasqResult struct {
	Verified             bool     `protobuf:"varint,1,opt,name=verified,proto3" json:"verified,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HasqResult) Reset()         { *m = HasqResult{} }
func (m *HasqResult) String() string { return proto.CompactTextString(m) }
func (*HasqResult) ProtoMessage()    {}
func (*HasqResult) Descriptor() ([]byte, []int) {
	return fileDescriptor_8f3733d4161a6cce, []int{1}
}

func (m *HasqResult) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HasqResult.Unmarshal(m, b)
}
func (m *HasqResult) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HasqResult.Marshal(b, m, deterministic)
}
func (m *HasqResult) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HasqResult.Merge(m, src)
}
func (m *HasqResult) XXX_Size() int {
	return xxx_messageInfo_HasqResult.Size(m)
}
func (m *HasqResult) XXX_DiscardUnknown() {
	xxx_messageInfo_HasqResult.DiscardUnknown(m)
}

var xxx_messageInfo_HasqResult proto.InternalMessageInfo

func (m *HasqResult) GetVerified() bool {
	if m != nil {
		return m.Verified
	}
	return false
}

func init() {
	proto.RegisterType((*HasqCreate)(nil), "simple.HasqCreate")
	proto.RegisterType((*HasqResult)(nil), "simple.HasqResult")
}

func init() { proto.RegisterFile("hasq_simple.proto", fileDescriptor_8f3733d4161a6cce) }

var fileDescriptor_8f3733d4161a6cce = []byte{
	// 225 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x54, 0x90, 0xb1, 0x4e, 0xc3, 0x30,
	0x10, 0x86, 0x09, 0x25, 0x51, 0x39, 0x16, 0x30, 0x0c, 0x56, 0xa7, 0x2a, 0x62, 0xc8, 0x94, 0xa1,
	0x3c, 0x01, 0x65, 0xe9, 0x88, 0xc2, 0x03, 0x54, 0xa6, 0xfd, 0x69, 0xa2, 0xb6, 0x76, 0xec, 0x73,
	0x0a, 0xbc, 0x3d, 0xb2, 0x5d, 0x05, 0xd8, 0xfc, 0x7d, 0xd2, 0xdd, 0xef, 0xff, 0xe8, 0xae, 0x55,
	0x6c, 0xd7, 0xdc, 0x1d, 0xfb, 0x03, 0xea, 0xde, 0x19, 0x6f, 0x44, 0x91, 0xa8, 0xfc, 0x22, 0x5a,
	0x29, 0xb6, 0x2f, 0x0e, 0xca, 0x43, 0xcc, 0x68, 0xca, 0xb0, 0x03, 0xf4, 0x06, 0x32, 0x9b, 0x67,
	0x55, 0xde, 0x8c, 0x2c, 0x1e, 0x28, 0xf7, 0x66, 0x0f, 0x2d, 0x2f, 0xe7, 0x59, 0x75, 0xdd, 0x24,
	0x10, 0xb7, 0x34, 0xd9, 0xe3, 0x5b, 0x4e, 0xa2, 0x0b, 0xcf, 0x60, 0x76, 0xd0, 0xf2, 0x2a, 0x99,
	0x1d, 0x74, 0x98, 0x34, 0x9f, 0x1a, 0x4e, 0xe6, 0x69, 0x32, 0x42, 0x59, 0xa5, 0xe4, 0x06, 0x3c,
	0x1c, 0x7c, 0x48, 0x3e, 0xc1, 0x75, 0x1f, 0x1d, 0xb6, 0x31, 0x79, 0xda, 0x8c, 0xbc, 0x78, 0xa6,
	0x9b, 0x95, 0xe2, 0xf6, 0x0d, 0xee, 0xd4, 0x6d, 0x20, 0x16, 0x54, 0x9c, 0xbf, 0x2b, 0xea, 0x73,
	0xa7, 0xdf, 0x0a, 0xb3, 0x7f, 0x2e, 0x2d, 0x2f, 0x2f, 0x96, 0x8f, 0x74, 0xef, 0x86, 0xba, 0x57,
	0xec, 0x8d, 0xab, 0x5b, 0xc5, 0xad, 0x5d, 0x1f, 0xcd, 0x76, 0xf9, 0x77, 0xef, 0x6b, 0xf6, 0x5e,
	0xc4, 0xdb, 0x3c, 0xfd, 0x04, 0x00, 0x00, 0xff, 0xff, 0x3d, 0x61, 0x1d, 0x1a, 0x30, 0x01, 0x00,
	0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// HashServiceClient is the client API for HashService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type HashServiceClient interface {
	Create(ctx context.Context, in *HasqCreate, opts ...grpc.CallOption) (*HasqResult, error)
}

type hashServiceClient struct {
	cc *grpc.ClientConn
}

func NewHashServiceClient(cc *grpc.ClientConn) HashServiceClient {
	return &hashServiceClient{cc}
}

func (c *hashServiceClient) Create(ctx context.Context, in *HasqCreate, opts ...grpc.CallOption) (*HasqResult, error) {
	out := new(HasqResult)
	err := c.cc.Invoke(ctx, "/simple.HashService/Create", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// HashServiceServer is the server API for HashService service.
type HashServiceServer interface {
	Create(context.Context, *HasqCreate) (*HasqResult, error)
}

func RegisterHashServiceServer(s *grpc.Server, srv HashServiceServer) {
	s.RegisterService(&_HashService_serviceDesc, srv)
}

func _HashService_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HasqCreate)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HashServiceServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/simple.HashService/Create",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HashServiceServer).Create(ctx, req.(*HasqCreate))
	}
	return interceptor(ctx, in, info, handler)
}

var _HashService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "simple.HashService",
	HandlerType: (*HashServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Create",
			Handler:    _HashService_Create_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "hasq_simple.proto",
}
