# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.24.1'
        cache-dependency-path: "**/*.sum"
    - run: go version

    - name: Go modules Cache # Docs: <https://git.io/JfAKn#go---modules>
      uses: actions/cache@v2
      id: go-cache
      with:
        path: ~/go/pkg/mod
        key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
        restore-keys: ${{ runner.os }}-go-
    
    - if: steps.go-cache.outputs.cache-hit != 'true'
      run: go mod download

    - name: Dependencies
      run: |
        go get .
        go mod edit -replace=google.golang.org/grpc=github.com/grpc/grpc-go@latest
        go mod tidy

    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -v ./...
